// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'exceptions', kind: "module", path: './exceptions.html', attributes: []},
{name: 'exceptions.InterruptedInputException', kind: "classdeclaration", path: './exceptions/InterruptedInputException.html', attributes: []},
{name: 'exceptions.InterruptedOutputException', kind: "classdeclaration", path: './exceptions/InterruptedOutputException.html', attributes: []},
{name: 'exceptions.InterruptedStreamException', kind: "classdeclaration", path: './exceptions/InterruptedStreamException.html', attributes: []},
{name: 'exceptions.RecoverableHellException', kind: "classdeclaration", path: './exceptions/RecoverableHellException.html', attributes: []},
{name: 'exceptions.RecoverableHellException.this', kind: "functiondeclaration", path: './exceptions/RecoverableHellException.this.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'exceptions.UserBehaviourException', kind: "classdeclaration", path: './exceptions/UserBehaviourException.html', attributes: []},
];
