// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'exceptions', kind: "module", path: './exceptions.html', attributes: []},
{name: 'exceptions.ArgumentException', kind: "classdeclaration", path: './exceptions/ArgumentException.html', attributes: []},
{name: 'exceptions.ArgumentException.this', kind: "functiondeclaration", path: './exceptions/ArgumentException.this.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'exceptions.IOException', kind: "classdeclaration", path: './exceptions/IOException.html', attributes: []},
{name: 'exceptions.IOException.this', kind: "functiondeclaration", path: './exceptions/IOException.this.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'exceptions.NetworkException', kind: "classdeclaration", path: './exceptions/NetworkException.html', attributes: []},
{name: 'exceptions.NetworkException.this', kind: "functiondeclaration", path: './exceptions/NetworkException.this.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
{name: 'exceptions.NotImplementedException', kind: "classdeclaration", path: './exceptions/NotImplementedException.html', attributes: []},
{name: 'exceptions.NotImplementedException.this', kind: "functiondeclaration", path: './exceptions/NotImplementedException.this.html', attributes: ["pure", "nothrow", "nogc", "safe"]},
];
